on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      #- name: 测试自然语言
      #  run: |
      #      curl -X POST "https://api.groq.com/openai/v1/chat/completions" -H "Authorization: Bearer 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" -H "Content-Type: application/json" -d '{"messages": [{"role": "user", "content": "用中文回答：如何把小米音箱连接ChatGPT"}], "model": "mixtral-8x7b-32768"}'
      - name: 服务
        run: python3 -m http.server
